title: Barnlåten
description: Föräldrakooperativ
brand: Barnlåten

address_street: Turkosgatan 1  
address_zip: 421 52
address_city: Västra Frölunda

rektor_namn: Anna Andersson
rektor_mail: rektor@barnlaten.se
rektor_telefon: 072-40 34 363

kontakt_mail: kontakt@barnlaten.se
kontakt_telefon: 072-40 34 364

styrelsen_mail: styrelsen@barnlaten.se

collections:
  index_parts:
    sort_by: index

# deployment
#host: 0.0.0.0
#port: 5000
